stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine
  before_script:
    - apk add git
    - git config --global user.email "seu-email@example.com"
    - git config --global user.name "Seu Nome"
  script:
    - git clone --depth 1 --branch main https://oauth2:${GITHUB_TOKEN}@gitlab.com/seu-usuario/seu-repo.git repo
    - cd repo
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/seu-usuario/seu-repo-github.git
    - git push --force github main
  only:
    - main
